### ISSUE TITLE
 doesn't work anymore, outdated chrome UA

### ISSUE THREAD

**Issue by gsantner** [miccar/wazapp#6]
![grafik](https://user-images.githubusercontent.com/6735650/61937733-0a4c7100-af7f-11e9-97ec-bb2457a3b13b.png)

**Comment by garethjax** [comment]
Same issue!

**Comment by miccar** [comment]
thanks for your interest, it works fine for me, do you have the same problem?
Thanks

**Comment by el-vinz** [comment]
Hi, I have the same problem too.

**Comment by vrigolon** [comment]
same here.. exactly same error message. Any way to update chrome/chromium version?
